name: lua automatic run
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库代码
        uses: actions/checkout@v4
      - name: 安装lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.4"

      - name: 获取消息
        id: get
        run: echo "message=${{ github.event.head_commit.message }}" >> "$GITHUB_OUTPUT"

      - name: 判断消息是数字并获取正确的文件路径
        run: echo "$(bash script/get_message.bash ${{steps.get.outputs.message}})"
